### ISSUE TITLE
Test failure with `rake jasmine:ci` but passes fine with `rake jasmine`

### ISSUE THREAD

**Issue by cannikin** [jasmine/jasmine-gem#242] opened 2015-04-07 18:41 UTC
Any hints as to what could be happening here? I've got a spec that runs fine in Chrome with `rake jasmine` but fails in the terminal with `rake jasmine:ci`. It's testing a Backbone.js comparator. It looks like it blows the stack trying to run the test:

```javascript
Entry = Backbone.Model.extend({});

Entries = Entries = Backbone.Collection.extend({
  model: CalCounter.Models.Entry,
  comparator: function(entry) {
    return -Date.parse(entry.get('ate_at'));
  }
});

// test
describe("CalCounter.Collections.Entries", function() {
  it("sorts entries by ate_at, newest first", function() {
    var first = new CalCounter.Models.Entry({ate_at: '2015-04-03 12:00'});
    var second = new CalCounter.Models.Entry({ate_at: '2015-04-01 09:00'});
    var third = new CalCounter.Models.Entry({ate_at: '2015-04-02 12:00'});
    var entries = new CalCounter.Collections.Entries([first, second, third]);

    expect(entries.at(0)).toEqual(first);
    expect(entries.at(1)).toEqual(third);
    expect(entries.at(2)).toEqual(second);
  });
});
```

Here's the stack trace: https://gist.github.com/cannikin/ac26ad79879b10926d68

I see a bunch of `<circular reference: Object>` in the output which is why I'm guessing the stack is overflowing. But why is it only a problem when PhantomJS is running things and not Chrome?

**Comment by slackersoft** [comment] 2015-04-08 22:14
What version of jasmine are you using?

The problem is basically that once the models are put into a collection they become cyclic. One of the models properties is the collection, the collection has an array of models, etc. One way to work around this would be to write a [custom equality tester](http://jasmine.github.io/edge/custom_equality.html) that knows to compare two `Backbone.Model` objects by looking at their `attributes` (I think that's what it's called).

**Comment by cannikin** [comment] 2015-04-08 22:45
I'm on 2.2.0 of Jasmine.

How come that cyclical nature doesn't cause a problem when running the tests in the browser, only through the CI?

I updated my test to check that the ID attribute matched instead of the whole object. Works like a charm, thanks!

**Comment by slackersoft** [comment] 2015-09-24 22:39
The cyclical nature usually causes problems specifically when trying to serialize the data from the browser out to either phantomjs or selenium (depending on which browsers you're using).

Or it could just be a difference between running the specs in Chrome vs running them in PhantomJS and what the maximum stack depth is.

Closing, since it sounds like you've got a fix that works for you.

**Closed by slackersoft** 2015-09-24 22:39 UTC
