### ISSUE TITLE
Force jasmine run to fail if any uncaught errors occur.

### ISSUE THREAD

**Issue by rjomada** [jasmine/jasmine-gem#262] opened 2016-02-26 23:16 UTC
This seems like a similar issue as this:

https://github.com/jasmine/jasmine/issues/326

To reproduce, you can introduce a compilation error in any spec and then rake jasmine:ci.

    describe "the problem", ->
      beforeEach ->
        generatesCompileError 'there should be a comma after this argument' ->
          'this error will skip the entire spec file without reporting an error and succeeding, the only indicator is the number of tests run."

We were using jasmine 2.3.1 and upgraded to 2.4 to try to fix this, but it was still around.

**Comment by roooodcastro** [comment] 2016-04-12 21:27
+1 for this.

I just spent an hour trying to figure out why my ES6 specs were working when I ran `rake jasmine`, but didn't even seem to load when I tried using `rake jasmine:ci`.

Jasmine should at least warn me of this instead of just swiping it under the rug and ignoring the files altogether.

**Comment by slackersoft** [comment] 2016-10-17 19:20
This looks like a duplicate of jasmine/jasmine#529 and something that needs to be handled in the core library. Closing this. Thanks for using Jasmine!

**Closed by slackersoft** 2016-10-17 19:20 UTC
Labels: Core Feature
